waypoints:
  - {id: 1, 'x': 0.5, 'y': 0.5, 'yaw': 0.0}
  - {id: 2, 'x': 4.0, 'y': 1.5, 'yaw': 0.0}
  - {id: 3, 'x': 2.0, 'y': 2.0, 'yaw': 0.0}
  - {id: 4, 'x': 1.0, 'y': 4.5, 'yaw': 0.0}
  - {id: 5, 'x': 4.5, 'y': 4.5, 'yaw': 0.0}
