arucos:
  - id: 30
    position:
      x: 0.0
      y: 2.5
    orientation: 3.14159

  - id: 31
    position:
      x: 2.5
      y: 5.0
    orientation: 1.5708

  - id: 32
    position:
      x: 5.0
      y: 2.5
    orientation: 0

  - id: 33
    position:
      x: 2.5
      y: 0.0
    orientation: -1.5708
