arucos:
  - id: 33  # (1)
    position:
      x: 1.5
      y: 0.0
    orientation: -1.5708

  - id: 1  # (2)
    position:
      x: 3.5
      y: 0.0
    orientation: -1.5708

  - id: 32  # (3)
    position:
      x: 5.0
      y: 1.5
    orientation: 0
  
  - id: 2  # (4)
    position:
      x: 5.0
      y: 3.5
    orientation: 0

  - id: 3  # (5)
    position:
      x: 4.0
      y: 5.0
    orientation: 1.5708

  - id: 31  # (6)
    position:
      x: 1.0
      y: 5.0
    orientation: 1.5708

  - id: 4  # (7)
    position:
      x: 0.0
      y: 3.5
    orientation: -3.14159
  
  - id: 30  # (8)
    position:
      x: 0.0
      y: 1.5
    orientation: -3.14159
